os:
  - linux
sudo: required
language: cpp
dist: trusty
env:
  - TRAVIS_NODE_VERSION="10.15.0"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      - valgrind
      - python-pip
before_install:
  - >-
    sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60
    --slave /usr/bin/g++ g++ /usr/bin/g++-6
  - sudo update-alternatives --config gcc
  - gcc -v
  - g++ -v
  - cmake --version
  - sudo pip install --upgrade pip
  - sudo pip install gcovr
install:
  - >-
    rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm &&
    (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source
    ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - node --version
  - npm --version
  - npm i
script:
  - sh ./build.sh Debug build-debug
  - cd build-debug
  - ctest -T memcheck && cat Testing/Temporary/MemoryChecker.*.log
  - make coverage
  - cd ..
  - sh ./build.sh Release build-release
